export = 'SV -> C\n' +
  'SF -> P\n' +
  'BP -> V\n' +
  'HC -> B\n' +
  'PK -> B\n' +
  'NF -> C\n' +
  'SN -> N\n' +
  'PF -> S\n' +
  'ON -> S\n' +
  'FC -> C\n' +
  'PN -> P\n' +
  'SC -> B\n' +
  'KS -> V\n' +
  'OS -> S\n' +
  'NC -> C\n' +
  'VH -> N\n' +
  'OH -> C\n' +
  'BB -> H\n' +
  'KV -> V\n' +
  'HP -> S\n' +
  'CP -> H\n' +
  'SO -> F\n' +
  'KK -> N\n' +
  'OO -> C\n' +
  'SH -> O\n' +
  'PB -> S\n' +
  'KP -> H\n' +
  'OC -> K\n' +
  'BN -> F\n' +
  'HH -> S\n' +
  'CH -> B\n' +
  'PC -> V\n' +
  'SB -> N\n' +
  'KO -> H\n' +
  'BH -> B\n' +
  'SK -> K\n' +
  'KF -> S\n' +
  'NH -> O\n' +
  'HN -> V\n' +
  'VN -> F\n' +
  'BC -> V\n' +
  'VP -> C\n' +
  'KN -> H\n' +
  'PV -> S\n' +
  'HB -> V\n' +
  'VV -> O\n' +
  'PO -> B\n' +
  'FN -> H\n' +
  'PP -> B\n' +
  'BF -> S\n' +
  'CB -> S\n' +
  'NK -> F\n' +
  'NO -> B\n' +
  'CC -> S\n' +
  'OF -> C\n' +
  'HS -> H\n' +
  'SP -> C\n' +
  'VB -> V\n' +
  'BK -> S\n' +
  'CO -> O\n' +
  'NS -> K\n' +
  'PH -> O\n' +
  'BV -> B\n' +
  'CK -> F\n' +
  'VC -> S\n' +
  'HK -> B\n' +
  'BO -> K\n' +
  'HV -> F\n' +
  'KC -> V\n' +
  'CN -> H\n' +
  'FS -> V\n' +
  'VS -> N\n' +
  'CF -> K\n' +
  'VO -> F\n' +
  'FH -> H\n' +
  'NB -> N\n' +
  'PS -> P\n' +
  'OK -> N\n' +
  'CV -> O\n' +
  'CS -> K\n' +
  'HO -> C\n' +
  'KB -> P\n' +
  'NN -> V\n' +
  'KH -> C\n' +
  'OB -> V\n' +
  'BS -> O\n' +
  'FB -> H\n' +
  'FF -> K\n' +
  'HF -> P\n' +
  'FO -> F\n' +
  'VF -> F\n' +
  'OP -> S\n' +
  'VK -> K\n' +
  'OV -> N\n' +
  'FK -> H\n' +
  'FP -> H\n' +
  'NV -> H\n' +
  'NP -> N\n' +
  'SS -> C\n' +
  'FV -> N';
